### ISSUE TITLE
将来会支持 APFS 格式吗

### ISSUE THREAD

**Issue by channingbox** [Thomas-Tsai/partclone#110]
将来会支持 APFS 格式吗

**Comment by Thomas-Tsai** [comment]
yes, we also received the same request on LFNW 2018 and start this development. We will do some research and should be support apfs if i have time to do that.

**Comment by megous** [comment]
There's some work on Linux driver for APFS which might be useful: https://github.com/eafer/linux-apfs/tree/for-merge/fs/apfs

**Comment by channingbox** [comment]
I think it will be soon.
