### ISSUE TITLE
Mount partclone special image format file?

### ISSUE THREAD

**Issue by adatum** [Thomas-Tsai/partclone#140]
Hello, is it possible to mount a cloned partition image file made with the special image format?

eg. `partclone.btrfs -c -s /dev/sda1 -o ~/image_sda1.pcl`

In this example, is there a way to mount and explore the contents of `image_sda1.pcl`?

**Comment by MSumulong** [comment]
You essentially have to "restore" the partclone image to a raw image file which you can then mount to a loop device (basically a virtual hard drive).

Restore the partclone image to a raw image file:
```bash
cat ~/image_sda1.pcl | sudo partclone.btrfs -r -W -s - -o raw.img
```

Then mount the raw image file to a loop device:
```
sudo mkdir -p /mnt/hd_loop_dev
sudo mount -o loop raw.img /mnt/hd_loop_dev
```

Hopefully, that works out for you.

**Comment by adatum** [comment]
@MSumulong Thank you, that workaround was successful for me!

Could you let me know what the `-W` flag is for? I could not find it in the documentation or man page.

**Comment by MSumulong** [comment]
If you run partclone.btrfs --help, you can see it sets up the loop device:

`-W   --restore_raw_file create special raw file for loop device`

**Comment by Thomas-Tsai** [comment]
yes,
years ago, a project partclone-utils could mount .pcl image as a read-only file system. I lost the original URL but still can find some people updating it. I read the code and am not very clear about it based on [NBD](https://github.com/vasi/partclone-utils/search?q=nbd).

please check:
https://github.com/vasi/partclone-utils
https://sourceforge.net/projects/partclone-utils/
