### ISSUE TITLE
Failure build partclone 0.3.14 with --enable xfs

### ISSUE THREAD

**Issue by brand1970** [Thomas-Tsai/partclone#146]
In Arch (up to date system) and with --enable xfs, the build fails with :
"xfs/include/xfs_mount.h:108:6: error: redeclaration of ‘enum xfs_ag_resv_type’

With --disable xfs, the build is completed normally.

With the same setup, and --enable xfs the partclone 0.3.13 build is completed normally.

**Comment by Thomas-Tsai** [comment]
sorry, i have no arch system can test, or in test plan. Recently i receive patch about xfs compile for gcc-10, maybe you can give a test!

You can download or pull partclone  0.3.15 right now!

**Comment by brand1970** [comment]
With 0.3.15 the build is completed normally. Thank you. !!
