### ISSUE TITLE
Feature request: option --print-unused-blocks

### ISSUE THREAD

**Issue by jowagner** [Thomas-Tsai/partclone#174]
Partclone's description suggests that it has the ability to analyse filesystems and to only include the blocks in a backup that are actually in use by the filesystem. Knowing these blocks can be useful for other purposes, e.g. to punch holes into an image file to make it (more) sparse. An option to output this blocklist (instead of a full image) would be useful. In principle, it should also be possible to extract this blocklist from an existing partclone image file or reading partclone output from a pipe.

Note that this is not the same as finding zero blocks (which would be easy to implemented as a stand-alone tool):
* Most filesystems do not wipe data blocks when they become no longer used, e.g. when a file is deleted.
* There may be data blocks filled with just zero bytes that are required to be zero, e.g. as part of a file. In the example application of punching holes into an image file, including these blocks would not be harmful, but it could be problematic in other applications (and for this example application the feature is not needed as zero blocks can easily be made sparse with `fallocate`).

**Comment by Thomas-Tsai** [comment]
Hi,

I believe different file systems should have different ways to handle/wipe some blocks as you mentioned before. Partclone can't change it and also can't find zero blocks. Partclone just read filesystem [bitmap](https://en.wikipedia.org/wiki/Free_space_bitmap) to find an available block, if the block is available, we do not need to clone it. So if the block is not available we need to clone the black weather is zero or not. 

You also can get the block [domain file](https://www.gnu.org/software/ddrescue/manual/ddrescue_manual.html)
The example is [from](https://superuser.com/questions/703207/why-cant-ddrescue-just-recover-blocks-used-by-the-filesystem)

```
# produce a domain file for NTFS partition on /dev/sda1
partclone.ntfs -s /dev/sda1 -D -o sda1.domain
# copy /dev/sda1 to /dev/sdb1 using ddrescue with domain log file
ddrescue --domain-log sda1.domain /dev/sda1 /dev/sdb1 rescue.log
```

By the way, ddrescue changed option to --domain-mapfile

```
NOTE: In versions of ddrescue
       prior to 1.20 the mapfile was called 'logfile'. The format is the same; only the name has changed.

       -m, --domain-mapfile=<file>
              restrict domain to finished blocks in <file>
```

BR, Thomas.

**Comment by jowagner** [comment]
Thanks. This sounds like `-D` outputs what I am looking for.

Reading the table on https://www.gnu.org/software/ddrescue/manual/ddrescue_manual.html#Mapfile-structure and the quoted meaning of `ddrescue --domain-mapfile`, I understand `+` means "used block" but without the latter information, this is not clear or even confusing was `+` and `?` mean (as one would expect that `ddrescue` will not copy blocks that have been marked as "finished" in a previous ddrescue run). Suggest to add something like "This is a human readable file in which + marks used block areas and ? marks free areas." to the `partclone -D` man page.

Triggering trim operations for unused areas of my filesystems would not solve the problem I am looking into, unless the respective tool has a debug option to create a log file listing the block areas.

**Comment by jowagner** [comment]
I see 2 occurrences in `/docs`: in `.8` and `.xml`. Should both be edited? Is there a conversion tool?

**Comment by Thomas-Tsai** [comment]
just edit XML files and use xsltproc to convert them to .8 files.
please check doc/Makefile.am

**Comment by jowagner** [comment]
Any objections to closing this issue? The feature already exists as `-D`.

**Comment by Thomas-Tsai** [comment]
yes, thank you.
