### ISSUE TITLE
domain mapfile is missing essential block(s) for btrfs

### ISSUE THREAD

**Issue by jowagner** [Thomas-Tsai/partclone#176]
An empty btrfs filesystem is damaged by punching holes into it for byte ranges reported as unsued (status `?`) by `partclone.btrfs -D`.

Version tested: v0.3.11 (931b4a45da7f84917a64817019943bd61c9d9229), shipped with openSUSE Leap 15.3

Steps to reproduce (first check `losetup list --all` that `/dev/loop0` is not in use; carefully adjust commands below if it is):
``` shell
dd if=/dev/zero bs=1024k count=0 seek=81920 of=filesystem.img
losetup --find --show filesystem.img
mkfs.btrfs -m single /dev/loop0
partclone.btrfs -D -s /dev/loop0 -o filesystem.map
```

Mapfile:
```
# Domain logfile created by unset_name v0.3.11
# Source: /dev/loop0
# Offset: 0x00000000
# current_pos  current_status
0x1400000000     ?
#      pos        size  status
0x00000000  0x00014000  +
0x00014000  0x000F0000  ?
0x00104000  0x00BFC000  +
0x00D00000  0x13FF300000  ?
```

Steps to reproduce (continued):
``` shell
../domain-map-2-punch-holes.py 0 filesystem.img < filesystem.map > punch-holes.sh
```

Punch script:
``` shell
fallocate -p -l 983040 -o 81920 filesystem.img
fallocate -p -l 85885714432 -o 13631488 filesystem.img
```

Steps to reproduce (continued):
```
losetup -d /dev/loop0
bash ./punch-holes.sh
losetup --find --show filesystem.img
btrfs check /dev/loop0
```

Output:
```
Opening filesystem to check...
checksum verify failed on 1064960 found E4E3BDB6 wanted 00000000
checksum verify failed on 1064960 found E4E3BDB6 wanted 00000000
bad tree block 1064960, bytenr mismatch, want=1064960, have=0
ERROR: cannot read chunk root
ERROR: cannot open file system
```

Workaround: Before running `partclone -D`, create filesystem with `-m dup` (or convert existing filesystem) to have redundant system data and metadata and repair data with `btrfs scrub` after punching holes. There is no guarantee that this prevents uncorrectable errors but it should reduce the likelihood of such errors. Example output:
```
scrub status for 84f44ed6-eaab-4b0f-8d0b-199100c62d74
        scrub started at Thu Feb 24 10:48:46 2022 and finished after 00:00:00
        total bytes scrubbed: 256.00KiB with 9 errors
        error details: super=1 csum=8
        corrected errors: 8, uncorrectable errors: 0, unverified errors: 0
```

Correctable scrub errors were also found for a filesystem with a history of adding some files and deleting a subset of files.

No corruption is found if using partclone's image format. So it appears that more blocks are backed up in this case:
``` shell
partclone.btrfs -c -s /dev/loop0 -o filesystem.pcl
losetup -d /dev/loop0
dd if=/dev/zero bs=1024k count=0 seek=81920 of=filesystem-new.img
losetup --find --show filesystem-new.img 
partclone.btrfs -r -s filesystem.pcl -o /dev/loop0 
btrfs check /dev/loop0
```

Helper script used above to convert mapfile to punch-holes script:
* https://gist.github.com/jowagner/4fa63bfedf0b3d9389550995505871c9

Related:
* Issue #174

**Comment by jowagner** [comment]
Maybe `ddrescue` uses a blocksize bigger than 16 KiB and copies data that the domain mapfile says doesn't need copying? 

Even more strange, `partclone.btrfs -c` says "Space in use: 131.1 KB = 8 Blocks" but the mapfile has over 12 MiB marked with `+`.

Do you have a tool to view the bitmap in a `.pcl` file? Would be interesting to see what blocks have a `1`.

**Comment by jowagner** [comment]
Pre-filling the first 400 MiB of `filesystem.img` with markers and inspecting the file after `mkfs.btrfs` and `punch-holes.sh` with `hexdump -C`, I can (1) confirm that `fallocate` behaves as expected and (2) that `mkfs.btrfs` writes non-zero data into the ranges 0x100000-0x1000c5, 0x103ebo-0x103fbf and 0x103fe0-0x103fff, as well as zero bytes to 0x14000-0xfffff.

**Comment by Thomas-Tsai** [comment]
Maybe we can use ddrescue-view to check it.

The used block is (total block - free block) recorded in the superblock. Some file systems do not include metadata, so the bitmap result is different.

I do not have a tool to display bits, but I see ddrescue-view maybe can show the bitmaps?!

**Comment by Thomas-Tsai** [comment]
I added mirror-super blocks and did the basic test, and the result is good.

The new domain file:

```
# Domain logfile created by partclone.btrfs v0.3.17
# Source: /dev/loop0
# Offset: 0x00000000
# current_pos  current_status
0x1400000000     ?
#      pos        size  status
0x00000000  0x00014000  +
0x00014000  0x000F0000  ?
0x00104000  0x00BFC000  +
0x00D00000  0x03300000  ?
0x04000000  0x00004000  +
0x04004000  0x13FBFFC000  ?
```
