### ISSUE TITLE
Document / clarify usage of partclone on mounted devices

### ISSUE THREAD

**Issue by Abdull** [Thomas-Tsai/partclone#181]
`partclone.ext4 -d -c -s /dev/nvme0n1p3 -o /mnt/nvme1/backups/partclone/nvme0n1p3.img` returns

```
Partclone v0.3.13 http://partclone.org
Starting to clone device (/dev/nvme0n1p3) to image (/mnt/nvme1/backups/partclone/nvme0n1p3.img)
device (/dev/nvme0n1p3) is mounted at /
error exit
Partclone fail, please check /var/log/partclone.log !
```

So does this mean that _partclone_ requires the to-be-backed-upped device to be unmounted?

If so, please document this on the website, man pages and the `README.md`.

**Comment by Thomas-Tsai** [comment]
Yes, it has to run with unmounted status and is similar to other blocked-based tools.

and added Limitations to README.md.
