### ISSUE TITLE
reiserfs.h?

### ISSUE THREAD

**Issue by pvoisin** [Thomas-Tsai/partclone#2]
Hi, I'm stuck while running ./configure. Here's what I'm getting (Fedora 16):

$ sudo ./configure --enable-ncursesw --enable-all
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether NLS is requested... yes
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for style of include used by make... GNU
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking dependency style of gcc... gcc3
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for shared library run path origin... done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for GNU gettext in libc... yes
checking whether to use NLS... yes
checking where the gettext function comes from... libc
checking for gcc... (cached) gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether gcc accepts -g... (cached) yes
checking for gcc option to accept ISO C89... (cached) none needed
checking dependency style of gcc... (cached) gcc3
checking for rm... /bin/rm
checking whether ln -s works... yes
checking for special C compiler options needed for large files... no
checking for _FILE_OFFSET_BITS value needed for large files... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for UUID... yes
checking for pthread_create in -lpthread... yes
configure: checking  for EXT2/3 Library and Header files ... ...
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking ext2fs/ext2fs.h usability... yes
checking ext2fs/ext2fs.h presence... yes
checking for ext2fs/ext2fs.h... yes
checking for ext2fs_initialize in -lext2fs... yes
checking version of libextfs... 1.41.14; suggest you upgrade the library!
configure: WARNING: Suggest upgrade your libextfs to 1.42 or newer version!
checking for aio_init in -lrt... yes
configure: checking  for XFS Library and Header files ... ...
checking xfs/libxfs.h usability... yes
checking xfs/libxfs.h presence... yes
checking for xfs/libxfs.h... yes
configure: checking  for Reiserfs Library and Header files ... ...
checking reiserfs/reiserfs.h usability... no
checking reiserfs/reiserfs.h presence... no
checking for reiserfs/reiserfs.h... no
configure: error: **\* reiserfs header files (reiserfs/reiserfs.h) not found

**Comment by cheese** [comment]
Or you can get the RPM's for CentOS from here:
http://pkgs.repoforge.org/progsreiserfs/
