### ISSUE TITLE
partclone.ntfs not created by make.

### ISSUE THREAD

**Issue by linuxandos2** [Thomas-Tsai/partclone#223]
configure says:
Support File System:
fuse.......... no, 
ext2/3/4...... yes, 1.47.0
reiserfs...... no, 
reiser4....... no, 
xfs........... yes, build-in
ntfs.......... yes, 
fat12/16/32... yes, build-in
exfat......... yes, build-in
hfs plus...... yes, build-in
apfs.......... yes, build-in
ufs .......... no, 
vmfs ......... no, 
jfs .......... no, 
btrfs......... yes, unknown
minix......... yes, build-in
f2fs.......... yes, build-in
nilfs2.........no, 

But partclone;ntfs is not build by make.

**Comment by linuxandos2** [comment]
but partclone.ntfs is not buid...

**Comment by Thomas-Tsai** [comment]
Hi,
what Linux distribution you are running?
for Ubuntu/Debian you can install via apt.

For source code compiles by yourself, you have to install libntfs or [ntfs3g-dev](https://packages.debian.org/bullseye/ntfs-3g-dev) first, and enable ntfs before make command.

**Comment by Thomas-Tsai** [comment]
I just updated the wiki page for compile in Debian, please check here:
https://github.com/Thomas-Tsai/partclone/wiki/Debian--Ubuntu#compile

**Comment by linuxandos2** [comment]
Distrbution: Linux From Scratch.
Installed ntfs-3g_ntfsprogs-2022.10.3
that installs Ntfs-3g  and ntfsprogs

**Comment by Thomas-Tsai** [comment]
cool, so your should run `./configure --enable-ntfs` to test library and headers. After that, run make to compile and create partclone.ntfs.

**Comment by linuxandos2** [comment]
I already ran  ./configure --enable-ntfs.
had to install ntfsprogs from the source.
ntfs-3g_ntfsprogs-2022.10.3 from blfs seems to miss ntfsprogs.
now partclone.ntfs is ok.
cheers and thanks alot.
closing
