### ISSUE TITLE
Verifying a clone

### ISSUE THREAD

**Issue by rdiez** [Thomas-Tsai/partclone#238]
I am using Clonezilla, which I believe uses Partclone behind the scene.

I am replacing an HDD with an SSD, but I don't trust the hardware very much, so I wanted to verify the clone results.

I have looked everywhere, and there are some commands options in this respect like --gen-sha1sum , --gen-chksum-for-files-in-dev  and partclone.chkimg .The trouble is, I am not sure how this works in practice.

I am guessing that Clonezilla / Partclone makes some adjustments when copying disks and partitions, especially when the destination disk is smaller than the source disk, so I guess that I cannot use dd to calculate and compare a checksum across both source and destination disks.

Is there a way to re-run Clonezilla or Partclone in some "verify" mode, so that they check that the data on the destination disk matches expectations? I am thinking of generating the data for the clone, but instead of writing it, reading and comparing it.

**Comment by Thomas-Tsai** [comment]
Hi,

I suggest creating a checksum before backup, and then you can check any file after restore.

Or just access the backup image before you restore. Some other projects may be helpful for your request, like

https://github.com/fiddyschmitt/clonezilla-util/tree/master
or
https://github.com/allvpv/partclone-nbd

**Comment by rdiez** [comment]
The suggested solutions are cumbersome and file-based, which means that they are very slow, and non-file data like the master boot record or filesystem journals would not be covered.
