### ISSUE TITLE
partclone.btrfs : segfault when calculating bitmap

### ISSUE THREAD

**Issue by sladecraven** [Thomas-Tsai/partclone#64]
I have a BTRFS boot partition of 16 Gb in one of my system, and i want to clone it. But each time i use partclone, if get a segmentation fault during the bitmap calculation. I can still clone it using with partimage/dd mode, of course, but it is quite slow.
This bug occurs with all latest Clonezilla versions, since august 2015 (not tested with previous versions).
Any idea or debug hints ?

**Comment by Thomas-Tsai** [comment]
Could you please leave more information?
1. version of btrfs
2. linux distribution? version?
3. mount option
4. btrfs partition data usage by df

and do you think it can be re-produce this issue and how to do that?

**Comment by sladecraven** [comment]
Btrfs version : v4.0+20150429 (official version of Opensuse 13.2)

Distrib : OpenSuse 13.2

Mount otions : /dev/sda1 on / type btrfs (rw,relatime,space_cache)

Part usage:
Data, single: total=9.00GiB, used=7.16GiB
System, single: total=32.00MiB, used=16.00KiB
Metadata, single: total=1.00GiB, used=178.58MiB
GlobalReserve, single: total=64.00MiB, used=0.00B

Note that the partition should be 16 GB, as shown by lsblk : 
├─sda1   8:1    0    16G  0 part /

**Comment by sladecraven** [comment]
I can reproduce it at will, always. It does not happen with other BTRFS partitions, so i suspect this one is a bit special, but i do no know why.

**Comment by Thomas-Tsai** [comment]
got it.
We actually never test btrfs from suse, I will try to fix this recently.

**Comment by Thomas-Tsai** [comment]
Hello,

I just finish my new flash opensuse 13.2 amd64 installation and clone by partclone 0.2.83 well. 
please help to  check your btrfs and could you manual run partclone  from clonezilla-live shell as root

btrfsck YOURBTRFS
partclone.btrfs -d3 -D -s YOURBTRFS -o domainfile -L logfile
and
btrfs-debug-tree YOURBTRFS > btrfs-tree.log

please sent logfile and btrfs-tree.log to me while segfault fail.

thank you.

**Comment by sladecraven** [comment]
Partclone log file : http://demo.ovh.eu/download/c939b4dc211f0caef3aee362e27ce703/btrfs.log.zip 
Debug tree log file : http://demo.ovh.eu/download/c939b4dc211f0caef3aee362e27ce703/btrfstree.log.zip

**Comment by Thomas-Tsai** [comment]
Hi

I just found the point to made  segfault fail. partclone.btrfs try to set block as used but those blocks are out of partition size. That's so tricky and I still need to re-produced this situation to fix it. Did you remember some operate of btrfs partition, eg: resize, snapshot or raid ... .

or

could you please run btrfs-image for us, btrfs-image is

    btrfs-image is used to create an image of a btrfs filesystem. All data will be zeroed, but metadata and the like is preserved. Mainly used for debugging purposes.

run it like:

    btrfs-image -s -w BTRFS-PARTITION file.btrfs-image

and please sent the file file.btrfs-image to us and we can try to fix this issue.

**Comment by sladecraven** [comment]
Yes, i get : 

Superblock bytenr is larger than device size
Open ctree failed
create failed (No such file or directory)

**Comment by Thomas-Tsai** [comment]
wow, but your error message like open btrfs fail, did you forgot umount before btrfs-image ?

**Comment by sladecraven** [comment]
oops, yes, image ongoing now. 
I discussed with my colleagues, and, yes, a partition resize has been done with gparted a while ago, so it seems to be the root cause of the issue. Any idea on how to fix it ?

**Comment by sladecraven** [comment]
BTRFS-IMAGE : http://demo.ovh.eu/download/dbb0509258415fd497cbd1b0c01890c2/TEST.IMG.zip

**Comment by Thomas-Tsai** [comment]
I have been test resize btrfs on  gparted-live 0.16.2-11 and 0.23.0-2. The old version will resize as small as possible but btrfs partition broken, I guess they fixed this after many release. Current version of gparted-live just shrink to last used black( i guess again). Anyway, partclone would not fix your btrfs but it can try to skip some metadata (out of size), therefore, you can finish the clone. I strongly recommend you restore image to different partition and run md5sum for each file to make sure they are save.

just release partclone_0.2.83~git544b, and give a try:
http://partclone.nchc.org.tw/download/experimental/partclone_0.2.83~git544b-1_i386.deb
http://sourceforge.net/projects/partclone/files/experimental/

please kindly let us know the result, thank you.

**Comment by sladecraven** [comment]
It seems to work, i have an image of the source partition. I am trying to clone it on a new partitions.

**Comment by Thomas-Tsai** [comment]
Thank You!
