### ISSUE TITLE
partclone.ntfs misses 4096 bytes

### ISSUE THREAD

**Issue by hds1** [Thomas-Tsai/partclone#69]
Probably double of #54 (Include Boot Sector)

When creating an ntfs-image with partclone  v0.2.83 the restored images misses one physical sector of 4096 bytes. Checked with various ntfs partitions.

Physical Device:
Disk /dev/sdc: 931.5 GiB, 1000204886016 bytes, 1953525168 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
Disklabel type: dos
Disk identifier: 0xf47a1902
Device     Boot  Start        End    Sectors   Size Id Type
/dev/sdc1  *      2048     206847     204800   100M  7 HPFS/NTFS/exFAT
/dev/sdc2       206848 1953521663 1953314816 931.4G  7 HPFS/NTFS/exFAT

Partclone Creation:
partclone.ntfs -c -o willi.img -s /dev/sdc2
Partclone Restore:
partclone.ntfs -r -s willi.img -o myimage.iso  (-W) Raw File does not make any difference.
myimage.iso cannot be loop mounted because of missing 4096 bytes.

On the other hand ntfsclone v2014.2.15 (libntfs-3g) works correct:
ntfsclone -s -o willi.img /dev/sdc2
resp. restore
ntfsclone -r -o myimage.iso willi.img
myimage.iso can be loop mounted and shows all NTFS files.

**Comment by Thomas-Tsai** [comment]
thank you for this report.
The new raw device size for restore image was re-build by bitmap and block size. For ntfs is not correct, we are already found the related issue/bug, and would be fix soon.

thank you!

**Comment by hds1** [comment]
Great. Thnak you very much for your effort.
