### ISSUE TITLE
Partclone.ntfs doesn't detect hibernated Windows 10 partition

### ISSUE THREAD

**Issue by arnova** [Thomas-Tsai/partclone#79]
By default Windows 10 uses "hybrid sleep" when the user shuts down the machine. When partclone.ntfs creates an image of the Windows partition when it's in that state, partclone.ntfs will happily create an image but the resulting image will be corrupted. This means that restoring such an image will result in an unbootable system. The proper (and simple) fix would simply be that partclone.ntfs detects the hibernated state (by eg. detecting the volume is dirty like ntfs-3g does) and refuse to image it.

**Comment by Thomas-Tsai** [comment]
thank you for this report, i will give a try next week because typhoon is comping!

**Comment by arnova** [comment]
Thanks a bunch! Note that I believe this is not an isolated issue, afaik only ntfs-3g is able to detect this state atm.

**Comment by arnova** [comment]
I've managed to figure out what's going on. Actually the problem is in ntfs-3g, not partclone. ntfs-3g is not able to detect non-hibernated state with Windows 10 NTFS partitions.

Sorry for the fuss. Closing this.
