### ISSUE TITLE
Update Brazilian Portuguese translation

### ISSUE THREAD

**Issue by rffontenelle** [Thomas-Tsai/partclone#81]
Please find attached the PO file: [pt_BR.zip](https://github.com/Thomas-Tsai/partclone/files/573113/pt_BR.zip)

**Comment by Thomas-Tsai** [comment]
thank you for this language support, just added to source code, and release in next version.

Thank You!

**Comment by rffontenelle** [comment]
Closing as implemented in fd1f3547
