### ISSUE TITLE
Incorrect FSF address

### ISSUE THREAD

**Issue by brouhaha** [Thomas-Tsai/partclone#83]
I'm packaging Partclone for Fedora Linux, and I'm required by Fedora policy to notify you that many files in the Partclone distribution contain an out-of-date postal address for the Free Software Foundation.

**Comment by Thomas-Tsai** [comment]
thank you for this notify, but I still have no idea about out-of-date postal address means.
do you have any suggestion? or some document about this

thank you

**Comment by brouhaha** [comment]
The Fedora information about it is here:
   https://fedoraproject.org/wiki/Common_Rpmlint_issues#incorrect-fsf-address
The current FSF address is 51 Franklin Street, Fifth Floor. Boston, MA 02110-1335
You may want to update that address in the GPL'd source files, but of course you aren't actually required to do anything.

**Comment by Thomas-Tsai** [comment]
okay, got it.
I will update or replace COPYING to "correct address is at GPL-2.0.txt"
thank you

**Comment by robert-scheck** [comment]
Pull request #70 actually suggests what @brouhaha is talking about.

**Comment by robert-scheck** [comment]
@Thomas-Tsai, could you please merge #98 simply? Thanks :)
