### ISSUE TITLE
read image_hdr totalblock error (v0.2.89)

### ISSUE THREAD

**Issue by steelstrings** [Thomas-Tsai/partclone#97]
when trying to raw restore a special image I get the following error "read image_hdr totalblock error"
after that I tried to restore it to partition and it gave the same error

the same happened with another image of a different harddrive

partclone.chkimg and partclone.info show the same error!

**Comment by Thomas-Tsai** [comment]
partclone.chkimg and partclone.info is work for partclone image, not raw file. please use partclone.dd to restore raw image.

**Comment by steelstrings** [comment]
It 'is' a special image, I just wanted to restore it to raw format, so I can mount it

**Comment by Thomas-Tsai** [comment]
try this option:
    -W   --restore_raw_file create special raw file for loop device

partclone.restore -d -s INPUT_IMAGE -O OUTPUT_FILE -W

sudo partclone.restore -d -s ./sda1.ext4-ptcl-img -O sda1_loop -W
Partclone v0.2.73 http://partclone.org
Starting to restore image (./sda1.ext4-ptcl-img) to device (sda1_loop)
Reading Super Block
Calculating bitmap... Please wait... done!
File system:  EXTFS
Device size:  524.3 MB = 512000 Blocks
Space in use: 123.2 MB = 120315 Blocks
Free Space:   401.1 MB = 391685 Blocks
Block size:   1024 Byte
Elapsed: 00:00:02, Remaining: 00:00:00, Completed: 100.00%, Rate:   3.70GB/min, 
current block:     401668, total block:     512000, Complete: 100.00%           
Total Time: 00:00:02, Ave. Rate:    3.7GB/min, 100.00% completed!
Syncing... OK!
Partclone successfully restored the image (./sda1.ext4-ptcl-img) to the device (sda1_loop)
Cloned successfully.
thomas@vm:/tmp2$ sudo mount -o loop sda1_loop /mnt/

**Comment by steelstrings** [comment]
no it doesn't work

**v0.2.89**
partclone.restore -d -s ssd_sdb3.s.img -O ssd_sdb3.img -W
Partclone v0.2.89 http://partclone.org
Starting to restore image (ssd_sdb3.s.img) to device (ssd_sdb3.img)
Reading Super Block
read image_hdr totalblock error
Partclone fail, please check /var/log/partclone.log !

**v0.2.73**
i tried to compile v0.2.73, but for some reason ./configure shows 'no' for every filesystem
partclone.restore -d -s ssd_sdb3.s.img -O ssd_sdb3.img -W
Partclone v0.2.73 http://partclone.org
Starting to restore image (ssd_sdb3.s.img) to device (ssd_sdb3.img)
Reading Super Block
This is not partclone image.
Partclone fail, please check /var/log/partclone.log !

/var/log/partclone.log shows the same error

For further clarification: I use '.s.img' for special image and '.img' for raw image

**Comment by Thomas-Tsai** [comment]
that's weird.
Is it possible to get the head of special image? we need first 512 byte by dd to check the image info.

Is the image clone by partclone 'v0.2' or partclone 'v0.3'?

**Comment by steelstrings** [comment]
sorry my mistake, I mistook this program for something else

actually I mixed up ntfsclone with partclone.ntfs, as I am normally using partclone.ext4
